
services:
  frontend:
    build: ./proxecto-front
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./proxecto-back/media:/usr/share/nginx/html/media
      - ./proxecto-back/staticfiles:/usr/share/nginx/html/static


  backend:
    build: ./proxecto-back
    env_file:
      - ./proxecto-back/.env
    command: sh -c "python manage.py collectstatic --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - database
    expose:
      - "8000"
    volumes:
      - ./proxecto-back/media:/app/media
      - ./proxecto-back/staticfiles:/app/staticfiles


  database:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: dataweb
    volumes:
      - "database-data:/var/lib/postgresql/data"

volumes:
  database-data:
